/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForgetPasswordRouteImport } from './routes/auth/forget-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAdminRouteImport } from './routes/auth/admin'
import { Route as DashboardLayoutRouteRouteImport } from './routes/dashboard/_layout/route'
import { Route as DashboardLayoutuserUserIndexRouteImport } from './routes/dashboard/_layout/(user)/user.index'
import { Route as DashboardLayoutadminAdminIndexRouteImport } from './routes/dashboard/_layout/(admin)/admin.index'
import { Route as DashboardLayoutuserUserTicketsRouteImport } from './routes/dashboard/_layout/(user)/user.tickets'
import { Route as DashboardLayoutuserUserSettingsRouteImport } from './routes/dashboard/_layout/(user)/user.settings'
import { Route as DashboardLayoutuserUserQuotationsRouteImport } from './routes/dashboard/_layout/(user)/user.quotations'
import { Route as DashboardLayoutadminAdminVisitsRouteImport } from './routes/dashboard/_layout/(admin)/admin.visits'
import { Route as DashboardLayoutadminAdminUsersRouteImport } from './routes/dashboard/_layout/(admin)/admin.users'
import { Route as DashboardLayoutadminAdminTicketsRouteImport } from './routes/dashboard/_layout/(admin)/admin.tickets'
import { Route as DashboardLayoutadminAdminSettingsRouteImport } from './routes/dashboard/_layout/(admin)/admin.settings'
import { Route as DashboardLayoutadminAdminReportsRouteImport } from './routes/dashboard/_layout/(admin)/admin.reports'
import { Route as DashboardLayoutadminAdminQuotationsRouteImport } from './routes/dashboard/_layout/(admin)/admin.quotations'
import { Route as DashboardLayoutadminAdminProfilesRouteImport } from './routes/dashboard/_layout/(admin)/admin.profiles'
import { Route as DashboardLayoutadminAdminProfileRouteImport } from './routes/dashboard/_layout/(admin)/admin.profile'
import { Route as DashboardLayoutadminAdminMetricsRouteImport } from './routes/dashboard/_layout/(admin)/admin.metrics'
import { Route as DashboardLayoutadminAdminLogsRouteImport } from './routes/dashboard/_layout/(admin)/admin.logs'
import { Route as DashboardLayoutadminAdminAdminsRouteImport } from './routes/dashboard/_layout/(admin)/admin.admins'

const DashboardRouteImport = createFileRoute('/dashboard')()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/auth/forget-password',
  path: '/auth/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRouteRoute = DashboardLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLayoutuserUserIndexRoute =
  DashboardLayoutuserUserIndexRouteImport.update({
    id: '/(user)/user/',
    path: '/user/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminIndexRoute =
  DashboardLayoutadminAdminIndexRouteImport.update({
    id: '/(admin)/admin/',
    path: '/admin/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutuserUserTicketsRoute =
  DashboardLayoutuserUserTicketsRouteImport.update({
    id: '/(user)/user/tickets',
    path: '/user/tickets',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutuserUserSettingsRoute =
  DashboardLayoutuserUserSettingsRouteImport.update({
    id: '/(user)/user/settings',
    path: '/user/settings',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutuserUserQuotationsRoute =
  DashboardLayoutuserUserQuotationsRouteImport.update({
    id: '/(user)/user/quotations',
    path: '/user/quotations',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminVisitsRoute =
  DashboardLayoutadminAdminVisitsRouteImport.update({
    id: '/(admin)/admin/visits',
    path: '/admin/visits',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminUsersRoute =
  DashboardLayoutadminAdminUsersRouteImport.update({
    id: '/(admin)/admin/users',
    path: '/admin/users',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminTicketsRoute =
  DashboardLayoutadminAdminTicketsRouteImport.update({
    id: '/(admin)/admin/tickets',
    path: '/admin/tickets',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminSettingsRoute =
  DashboardLayoutadminAdminSettingsRouteImport.update({
    id: '/(admin)/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminReportsRoute =
  DashboardLayoutadminAdminReportsRouteImport.update({
    id: '/(admin)/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminQuotationsRoute =
  DashboardLayoutadminAdminQuotationsRouteImport.update({
    id: '/(admin)/admin/quotations',
    path: '/admin/quotations',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminProfilesRoute =
  DashboardLayoutadminAdminProfilesRouteImport.update({
    id: '/(admin)/admin/profiles',
    path: '/admin/profiles',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminProfileRoute =
  DashboardLayoutadminAdminProfileRouteImport.update({
    id: '/(admin)/admin/profile',
    path: '/admin/profile',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminMetricsRoute =
  DashboardLayoutadminAdminMetricsRouteImport.update({
    id: '/(admin)/admin/metrics',
    path: '/admin/metrics',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminLogsRoute =
  DashboardLayoutadminAdminLogsRouteImport.update({
    id: '/(admin)/admin/logs',
    path: '/admin/logs',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutadminAdminAdminsRoute =
  DashboardLayoutadminAdminAdminsRouteImport.update({
    id: '/(admin)/admin/admins',
    path: '/admin/admins',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteRouteWithChildren
  '/auth/admin': typeof AuthAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/admin/admins': typeof DashboardLayoutadminAdminAdminsRoute
  '/dashboard/admin/logs': typeof DashboardLayoutadminAdminLogsRoute
  '/dashboard/admin/metrics': typeof DashboardLayoutadminAdminMetricsRoute
  '/dashboard/admin/profile': typeof DashboardLayoutadminAdminProfileRoute
  '/dashboard/admin/profiles': typeof DashboardLayoutadminAdminProfilesRoute
  '/dashboard/admin/quotations': typeof DashboardLayoutadminAdminQuotationsRoute
  '/dashboard/admin/reports': typeof DashboardLayoutadminAdminReportsRoute
  '/dashboard/admin/settings': typeof DashboardLayoutadminAdminSettingsRoute
  '/dashboard/admin/tickets': typeof DashboardLayoutadminAdminTicketsRoute
  '/dashboard/admin/users': typeof DashboardLayoutadminAdminUsersRoute
  '/dashboard/admin/visits': typeof DashboardLayoutadminAdminVisitsRoute
  '/dashboard/user/quotations': typeof DashboardLayoutuserUserQuotationsRoute
  '/dashboard/user/settings': typeof DashboardLayoutuserUserSettingsRoute
  '/dashboard/user/tickets': typeof DashboardLayoutuserUserTicketsRoute
  '/dashboard/admin': typeof DashboardLayoutadminAdminIndexRoute
  '/dashboard/user': typeof DashboardLayoutuserUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteRouteWithChildren
  '/auth/admin': typeof AuthAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/admin/admins': typeof DashboardLayoutadminAdminAdminsRoute
  '/dashboard/admin/logs': typeof DashboardLayoutadminAdminLogsRoute
  '/dashboard/admin/metrics': typeof DashboardLayoutadminAdminMetricsRoute
  '/dashboard/admin/profile': typeof DashboardLayoutadminAdminProfileRoute
  '/dashboard/admin/profiles': typeof DashboardLayoutadminAdminProfilesRoute
  '/dashboard/admin/quotations': typeof DashboardLayoutadminAdminQuotationsRoute
  '/dashboard/admin/reports': typeof DashboardLayoutadminAdminReportsRoute
  '/dashboard/admin/settings': typeof DashboardLayoutadminAdminSettingsRoute
  '/dashboard/admin/tickets': typeof DashboardLayoutadminAdminTicketsRoute
  '/dashboard/admin/users': typeof DashboardLayoutadminAdminUsersRoute
  '/dashboard/admin/visits': typeof DashboardLayoutadminAdminVisitsRoute
  '/dashboard/user/quotations': typeof DashboardLayoutuserUserQuotationsRoute
  '/dashboard/user/settings': typeof DashboardLayoutuserUserSettingsRoute
  '/dashboard/user/tickets': typeof DashboardLayoutuserUserTicketsRoute
  '/dashboard/admin': typeof DashboardLayoutadminAdminIndexRoute
  '/dashboard/user': typeof DashboardLayoutuserUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRouteRouteWithChildren
  '/auth/admin': typeof AuthAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/_layout/(admin)/admin/admins': typeof DashboardLayoutadminAdminAdminsRoute
  '/dashboard/_layout/(admin)/admin/logs': typeof DashboardLayoutadminAdminLogsRoute
  '/dashboard/_layout/(admin)/admin/metrics': typeof DashboardLayoutadminAdminMetricsRoute
  '/dashboard/_layout/(admin)/admin/profile': typeof DashboardLayoutadminAdminProfileRoute
  '/dashboard/_layout/(admin)/admin/profiles': typeof DashboardLayoutadminAdminProfilesRoute
  '/dashboard/_layout/(admin)/admin/quotations': typeof DashboardLayoutadminAdminQuotationsRoute
  '/dashboard/_layout/(admin)/admin/reports': typeof DashboardLayoutadminAdminReportsRoute
  '/dashboard/_layout/(admin)/admin/settings': typeof DashboardLayoutadminAdminSettingsRoute
  '/dashboard/_layout/(admin)/admin/tickets': typeof DashboardLayoutadminAdminTicketsRoute
  '/dashboard/_layout/(admin)/admin/users': typeof DashboardLayoutadminAdminUsersRoute
  '/dashboard/_layout/(admin)/admin/visits': typeof DashboardLayoutadminAdminVisitsRoute
  '/dashboard/_layout/(user)/user/quotations': typeof DashboardLayoutuserUserQuotationsRoute
  '/dashboard/_layout/(user)/user/settings': typeof DashboardLayoutuserUserSettingsRoute
  '/dashboard/_layout/(user)/user/tickets': typeof DashboardLayoutuserUserTicketsRoute
  '/dashboard/_layout/(admin)/admin/': typeof DashboardLayoutadminAdminIndexRoute
  '/dashboard/_layout/(user)/user/': typeof DashboardLayoutuserUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/admin'
    | '/auth/callback'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/admin/admins'
    | '/dashboard/admin/logs'
    | '/dashboard/admin/metrics'
    | '/dashboard/admin/profile'
    | '/dashboard/admin/profiles'
    | '/dashboard/admin/quotations'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/tickets'
    | '/dashboard/admin/users'
    | '/dashboard/admin/visits'
    | '/dashboard/user/quotations'
    | '/dashboard/user/settings'
    | '/dashboard/user/tickets'
    | '/dashboard/admin'
    | '/dashboard/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/admin'
    | '/auth/callback'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/admin/admins'
    | '/dashboard/admin/logs'
    | '/dashboard/admin/metrics'
    | '/dashboard/admin/profile'
    | '/dashboard/admin/profiles'
    | '/dashboard/admin/quotations'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/tickets'
    | '/dashboard/admin/users'
    | '/dashboard/admin/visits'
    | '/dashboard/user/quotations'
    | '/dashboard/user/settings'
    | '/dashboard/user/tickets'
    | '/dashboard/admin'
    | '/dashboard/user'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/_layout'
    | '/auth/admin'
    | '/auth/callback'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/_layout/(admin)/admin/admins'
    | '/dashboard/_layout/(admin)/admin/logs'
    | '/dashboard/_layout/(admin)/admin/metrics'
    | '/dashboard/_layout/(admin)/admin/profile'
    | '/dashboard/_layout/(admin)/admin/profiles'
    | '/dashboard/_layout/(admin)/admin/quotations'
    | '/dashboard/_layout/(admin)/admin/reports'
    | '/dashboard/_layout/(admin)/admin/settings'
    | '/dashboard/_layout/(admin)/admin/tickets'
    | '/dashboard/_layout/(admin)/admin/users'
    | '/dashboard/_layout/(admin)/admin/visits'
    | '/dashboard/_layout/(user)/user/quotations'
    | '/dashboard/_layout/(user)/user/settings'
    | '/dashboard/_layout/(user)/user/tickets'
    | '/dashboard/_layout/(admin)/admin/'
    | '/dashboard/_layout/(user)/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthAdminRoute: typeof AuthAdminRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forget-password': {
      id: '/auth/forget-password'
      path: '/auth/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_layout/(user)/user/': {
      id: '/dashboard/_layout/(user)/user/'
      path: '/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardLayoutuserUserIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/': {
      id: '/dashboard/_layout/(admin)/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardLayoutadminAdminIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(user)/user/tickets': {
      id: '/dashboard/_layout/(user)/user/tickets'
      path: '/user/tickets'
      fullPath: '/dashboard/user/tickets'
      preLoaderRoute: typeof DashboardLayoutuserUserTicketsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(user)/user/settings': {
      id: '/dashboard/_layout/(user)/user/settings'
      path: '/user/settings'
      fullPath: '/dashboard/user/settings'
      preLoaderRoute: typeof DashboardLayoutuserUserSettingsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(user)/user/quotations': {
      id: '/dashboard/_layout/(user)/user/quotations'
      path: '/user/quotations'
      fullPath: '/dashboard/user/quotations'
      preLoaderRoute: typeof DashboardLayoutuserUserQuotationsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/visits': {
      id: '/dashboard/_layout/(admin)/admin/visits'
      path: '/admin/visits'
      fullPath: '/dashboard/admin/visits'
      preLoaderRoute: typeof DashboardLayoutadminAdminVisitsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/users': {
      id: '/dashboard/_layout/(admin)/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardLayoutadminAdminUsersRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/tickets': {
      id: '/dashboard/_layout/(admin)/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/dashboard/admin/tickets'
      preLoaderRoute: typeof DashboardLayoutadminAdminTicketsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/settings': {
      id: '/dashboard/_layout/(admin)/admin/settings'
      path: '/admin/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardLayoutadminAdminSettingsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/reports': {
      id: '/dashboard/_layout/(admin)/admin/reports'
      path: '/admin/reports'
      fullPath: '/dashboard/admin/reports'
      preLoaderRoute: typeof DashboardLayoutadminAdminReportsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/quotations': {
      id: '/dashboard/_layout/(admin)/admin/quotations'
      path: '/admin/quotations'
      fullPath: '/dashboard/admin/quotations'
      preLoaderRoute: typeof DashboardLayoutadminAdminQuotationsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/profiles': {
      id: '/dashboard/_layout/(admin)/admin/profiles'
      path: '/admin/profiles'
      fullPath: '/dashboard/admin/profiles'
      preLoaderRoute: typeof DashboardLayoutadminAdminProfilesRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/profile': {
      id: '/dashboard/_layout/(admin)/admin/profile'
      path: '/admin/profile'
      fullPath: '/dashboard/admin/profile'
      preLoaderRoute: typeof DashboardLayoutadminAdminProfileRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/metrics': {
      id: '/dashboard/_layout/(admin)/admin/metrics'
      path: '/admin/metrics'
      fullPath: '/dashboard/admin/metrics'
      preLoaderRoute: typeof DashboardLayoutadminAdminMetricsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/logs': {
      id: '/dashboard/_layout/(admin)/admin/logs'
      path: '/admin/logs'
      fullPath: '/dashboard/admin/logs'
      preLoaderRoute: typeof DashboardLayoutadminAdminLogsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/(admin)/admin/admins': {
      id: '/dashboard/_layout/(admin)/admin/admins'
      path: '/admin/admins'
      fullPath: '/dashboard/admin/admins'
      preLoaderRoute: typeof DashboardLayoutadminAdminAdminsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
  }
}

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutadminAdminAdminsRoute: typeof DashboardLayoutadminAdminAdminsRoute
  DashboardLayoutadminAdminLogsRoute: typeof DashboardLayoutadminAdminLogsRoute
  DashboardLayoutadminAdminMetricsRoute: typeof DashboardLayoutadminAdminMetricsRoute
  DashboardLayoutadminAdminProfileRoute: typeof DashboardLayoutadminAdminProfileRoute
  DashboardLayoutadminAdminProfilesRoute: typeof DashboardLayoutadminAdminProfilesRoute
  DashboardLayoutadminAdminQuotationsRoute: typeof DashboardLayoutadminAdminQuotationsRoute
  DashboardLayoutadminAdminReportsRoute: typeof DashboardLayoutadminAdminReportsRoute
  DashboardLayoutadminAdminSettingsRoute: typeof DashboardLayoutadminAdminSettingsRoute
  DashboardLayoutadminAdminTicketsRoute: typeof DashboardLayoutadminAdminTicketsRoute
  DashboardLayoutadminAdminUsersRoute: typeof DashboardLayoutadminAdminUsersRoute
  DashboardLayoutadminAdminVisitsRoute: typeof DashboardLayoutadminAdminVisitsRoute
  DashboardLayoutuserUserQuotationsRoute: typeof DashboardLayoutuserUserQuotationsRoute
  DashboardLayoutuserUserSettingsRoute: typeof DashboardLayoutuserUserSettingsRoute
  DashboardLayoutuserUserTicketsRoute: typeof DashboardLayoutuserUserTicketsRoute
  DashboardLayoutadminAdminIndexRoute: typeof DashboardLayoutadminAdminIndexRoute
  DashboardLayoutuserUserIndexRoute: typeof DashboardLayoutuserUserIndexRoute
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutadminAdminAdminsRoute: DashboardLayoutadminAdminAdminsRoute,
  DashboardLayoutadminAdminLogsRoute: DashboardLayoutadminAdminLogsRoute,
  DashboardLayoutadminAdminMetricsRoute: DashboardLayoutadminAdminMetricsRoute,
  DashboardLayoutadminAdminProfileRoute: DashboardLayoutadminAdminProfileRoute,
  DashboardLayoutadminAdminProfilesRoute:
    DashboardLayoutadminAdminProfilesRoute,
  DashboardLayoutadminAdminQuotationsRoute:
    DashboardLayoutadminAdminQuotationsRoute,
  DashboardLayoutadminAdminReportsRoute: DashboardLayoutadminAdminReportsRoute,
  DashboardLayoutadminAdminSettingsRoute:
    DashboardLayoutadminAdminSettingsRoute,
  DashboardLayoutadminAdminTicketsRoute: DashboardLayoutadminAdminTicketsRoute,
  DashboardLayoutadminAdminUsersRoute: DashboardLayoutadminAdminUsersRoute,
  DashboardLayoutadminAdminVisitsRoute: DashboardLayoutadminAdminVisitsRoute,
  DashboardLayoutuserUserQuotationsRoute:
    DashboardLayoutuserUserQuotationsRoute,
  DashboardLayoutuserUserSettingsRoute: DashboardLayoutuserUserSettingsRoute,
  DashboardLayoutuserUserTicketsRoute: DashboardLayoutuserUserTicketsRoute,
  DashboardLayoutadminAdminIndexRoute: DashboardLayoutadminAdminIndexRoute,
  DashboardLayoutuserUserIndexRoute: DashboardLayoutuserUserIndexRoute,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

interface DashboardRouteChildren {
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthAdminRoute: AuthAdminRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
